// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4r1gT_VxvV1nqkB7EkwwXC0JFbm0vwNk',
    appId: '1:881771333733:android:aa65b1f0c591a62d2c5e8c',
    messagingSenderId: '881771333733',
    projectId: 'fit-verse-c3088',
    storageBucket: 'fit-verse-c3088.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAcFwn3M_RuHtj0kX1Rvr_8LIRf1CBqSM',
    appId: '1:881771333733:ios:b1334388a83137332c5e8c',
    messagingSenderId: '881771333733',
    projectId: 'fit-verse-c3088',
    storageBucket: 'fit-verse-c3088.firebasestorage.app',
    iosBundleId: 'com.example.fitVerse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3aioDJLwiNt_GDotH2T_jO1JCD5hysuM',
    appId: '1:881771333733:web:9aef7150c8ff02a12c5e8c',
    messagingSenderId: '881771333733',
    projectId: 'fit-verse-c3088',
    authDomain: 'fit-verse-c3088.firebaseapp.com',
    storageBucket: 'fit-verse-c3088.firebasestorage.app',
    measurementId: 'G-CPTTCQVL6R',
  );

}